const data = {
    product: [
        {
            id: 1,
            name: "Abroad Keke",
            price: 240,
            img: "https://picsum.photos/id/45/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 2,
            name: "Just Forks",
            price: 230,
            img: "https://picsum.photos/id/23/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'gifts',
        },
        {
            id: 3,
            name: "Chancema",
            price: 400,
            img: "https://picsum.photos/id/435/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 4,
            name: "Karlsson Cam",
            price: 300,
            img: 'https://picsum.photos/id/319/300/200',
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 5,
            name: "Tea mug without Tea inside",
            price: 250,
            img: "https://picsum.photos/id/30/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'gifts',
        },
        {
            id: 6,
            name: "Old Bike with Free House",
            price: 250.94,
            img: "https://picsum.photos/id/76/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 7,
            name: "The Cam",
            price: 3050.00,
            img: "https://picsum.photos/id/250/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 8,
            name: "Old Women shoes",
            price: 300.34,
            img: "https://picsum.photos/id/21/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'ladies',
        },
        {
            id: 9,
            name: "Mac Book with Free Glasses and Mouse",
            price: 740.50,
            img: "https://picsum.photos/id/201/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 10,
            name: "Mac Book with Tea",
            price: 250,
            img: "https://picsum.photos/id/2/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 11,
            name: "Danfo - Shipped from abroad",
            price: 670.88,
            img: "https://picsum.photos/id/183/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 12,
            name: "Mac with a Book and Pen",
            price: 560.60,
            img: "https://picsum.photos/id/180/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'technology',
        },
        {
            id: 13,
            name: "I Can’t Believe It’s a Clock!",
            price: 156.56,
            img: "https://picsum.photos/id/175/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'gifts',
        },
        {
            id: 14,
            name: "2 in 1 - Very nice ride",
            price: 400,
            img: "https://picsum.photos/id/133/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 15,
            name: "Old but new Car",
            price: 230.40,
            img: "https://picsum.photos/id/111/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 16,
            name: "Old Lion",
            price: 2450.93,
            img: "https://picsum.photos/id/1074/300/200",
            desc: "lorem ipsum et - it does not bite. Very friendly with humans.",
            category: 'animals',
        },
        {
            id: 17,
            name: "Old car with Tires That Rock",
            price: 50.98,
            img: "https://picsum.photos/id/1072/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'vehicles',
        },
        {
            id: 18,
            name: "I Can’t Believe It’s a Wrapped Dog!",
            price: 800.50,
            img: "https://picsum.photos/id/1062/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'animals',
        },
        {
            id: 19,
            name: "Torn Holy Bible",
            price: 150.99,
            img: "https://picsum.photos/id/1010/300/200",
            desc: "lorem ipsum et gyukt ytgyleiglfu yjgfEYKFGEY YGJGF grgwru glfrgfrlgflrh",
            category: 'gifts',
        }
    ]
}
export default data;