const data = {
    product: [
        {
            id: 1,
            name: "Abroad Keke",
            price: 240,
            old_price: 500,
            img: "https://picsum.photos/id/45/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 5,
            availability: 'in stock',
        },
        {
            id: 2,
            name: "Just Forks",
            price: 230,
            old_price: 460,
            img: "https://picsum.photos/id/23/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'gifts',
            rating: 2,
            availability: 'in stock',
        },
        {
            id: 3,
            name: "Chancema",
            price: 400,
            old_price: 800,
            img: "https://picsum.photos/id/435/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 4,
            availability: 'in stock',
        },
        {
            id: 4,
            name: "Karlsson Cam",
            price: 300,
            old_price: 600,
            img: 'https://picsum.photos/id/319/300/200',
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 4,
            availability: 'in stock',
        },
        {
            id: 5,
            name: "Tea mug without Tea inside",
            price: 250,
            old_price: 420,
            img: "https://picsum.photos/id/30/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'gifts',
            rating: 0,
            availability: 'in stock',
        },
        {
            id: 6,
            name: "Old Bike with Free House",
            price: 250.94,
            old_price: 500.20,
            img: "https://picsum.photos/id/76/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 1,
            availability: 'out of stock',
        },
        {
            id: 7,
            name: "The Cam",
            price: 3050.00,
            old_price: 5000.90,
            img: "https://picsum.photos/id/250/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 5,
            availability: 'in stock',
        },
        {
            id: 8,
            name: "Old Women shoes",
            price: 300.34,
            old_price: 700.90,
            img: "https://picsum.photos/id/21/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'ladies',
            rating: 2,
            availability: 'in stock',
        },
        {
            id: 9,
            name: "Mac Book with Free Glasses and Mouse",
            price: 740.50,
            img: "https://picsum.photos/id/201/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 5,
            availability: 'in stock',
        },
        {
            id: 10,
            name: "Mac Book with Tea",
            price: 250,
            old_price: 600,
            img: "https://picsum.photos/id/2/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 3,
            availability: 'in stock',
        },
        {
            id: 11,
            name: "Danfo - Shipped from abroad",
            price: 670.88,
            old_price: 1000,
            img: "https://picsum.photos/id/183/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 2,
            availability: 'in stock',
        },
        {
            id: 12,
            name: "Mac with a Book and Pen",
            price: 560.60,
            img: "https://picsum.photos/id/180/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'technology',
            rating: 4,
            availability: 'in stock',
        },
        {
            id: 13,
            name: "I Can’t Believe It’s a Clock!",
            price: 156.56,
            old_price: 200,
            img: "https://picsum.photos/id/175/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'gifts',
            rating: 0,
            availability: 'in stock',
        },
        {
            id: 14,
            name: "2 in 1 - Very nice ride",
            price: 400,
            old_price: 450,
            img: "https://picsum.photos/id/133/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 0,
            availability: 'in stock',
        },
        {
            id: 15,
            name: "Old but new Car",
            price: 230.40,
            old_price: 300.50,
            img: "https://picsum.photos/id/111/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 5,
            availability: 'in stock',
        },
        {
            id: 16,
            name: "Old Lion",
            price: 2450.93,
            img: "https://picsum.photos/id/1074/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'animals',
            rating: 0,
            availability: 'out of stock',
        },
        {
            id: 17,
            name: "Old car with Tires That Rock",
            price: 50.98,
            old_price: 90.50,
            img: "https://picsum.photos/id/1072/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'vehicles',
            rating: 2,
            availability: 'in stock',
        },
        {
            id: 18,
            name: "I Can’t Believe It’s a Wrapped Dog!",
            price: 800.50,
            old_price: 1000.50,
            img: "https://picsum.photos/id/1062/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'animals',
            rating: 4,
            availability: 'in stock',
        },
        {
            id: 19,
            name: "Torn Holy Bible",
            price: 150.99,
            img: "https://picsum.photos/id/1010/300/200",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed lobortis diam, in feugiat leo. Pellentesque suscipit consectetur risus, ullamcorper tristique magna venenatis ut. Etiam eget enim et nibh scelerisque congue in sed ante. Ut vitae lacus in ex iaculis porttitor. Maecenas auctor vel nisl at commodo. Sed erat est, dapibus sed pellentesque eu, euismod eget metus. Phasellus nulla ipsum, cursus at tempor nec, faucibus sed ligula. ",
            category: 'gifts',
            rating: 0,
            availability: 'in stock',
        }
    ]
}
export default data;